services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "8554:8554/udp"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
      - "1935:1935"
      - "9997:9997"
    volumes:
      - ./infra/mediamtx/mediamtx.yml:/mediamtx.yml:ro
