import { Camera, LayoutDashboard, MapPin, Settings, Video } from "lucide-react";
import { CCTVItem, CCTVSortKey, KoperasiSummary, IpCctv } from "./types";

export const NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "map",       label: "Peta Koperasi", icon: MapPin,     active: true },
  { id: "cctv",      label: "Manajemen CCTV", icon: Camera },
  { id: "recording", label: "Rekaman",         icon: Video },
  { id: "settings",  label: "Pengaturan",      icon: Settings },
];

// ─── MOCK DATA ────────────────────────────────────────────────────
export const KOPERASI_LIST: KoperasiSummary[] = [
  { id: "1", name: "KSP Sejahtera Mandiri", city: "Surabaya", province: "Jawa Timur", onlineCCTV: 7, totalCCTV: 8, lat: -6.93136, lng: 110.82637 },
  { id: "2", name: "KUD Mitra Tani", city: "Sidoarjo", province: "Jawa Timur", onlineCCTV: 8, totalCCTV: 8, lat: -6.72636, lng: 111.55538 },
  { id: "3", name: "Kopkar Nusantara", city: "Gresik", province: "Jawa Timur", onlineCCTV: 5, totalCCTV: 8, lat: -7.6565, lng: 110.89875 },
  { id: "4", name: "KSP Bumi Artha", city: "Jakarta", province: "DKI Jakarta", onlineCCTV: 8, totalCCTV: 8, lat: -6.2088, lng: 106.8456 },
  { id: "5", name: "KUD Karya Bersama", city: "Bandung", province: "Jawa Barat", onlineCCTV: 6, totalCCTV: 8, lat: -6.9175, lng: 107.6191 },
];

export const cols: ReadonlyArray<{ key: CCTVSortKey; label: string }> = [
    { key: "label",      label: "Label" },
    { key: "location",   label: "Lokasi" },
    { key: "status",     label: "Status" },
    { key: "resolution", label: "Resolusi" },
    { key: "brand",      label: "Brand" },
    { key: "fps",        label: "FPS" },
];

// IP CCTV Dummy Data
const IP_CCTV_DATA: Record<string, IpCctv> = {
  c1: {
    id: "ip1",
    ipAddress: "192.168.1.100",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Hikvision@123",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Main entrance CCTV",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  c2: {
    id: "ip2",
    ipAddress: "192.168.1.101",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Dahua@456",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Lobby camera",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  c3: {
    id: "ip3",
    ipAddress: "192.168.1.102",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Axis@789",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Cashier 1",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  c4: {
    id: "ip4",
    ipAddress: "192.168.1.103",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Hikvision@123",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Cashier 2 (Currently offline)",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c4",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  c5: {
    id: "ip5",
    ipAddress: "192.168.1.104",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Dahua@456",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Warehouse storage",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  c6: {
    id: "ip6",
    ipAddress: "192.168.1.105",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Axis@789",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Server room (Maintenance)",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  c7: {
    id: "ip7",
    ipAddress: "192.168.1.106",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Hikvision@123",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Parking area",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  c8: {
    id: "ip8",
    ipAddress: "192.168.1.107",
    port: 8080,
    protocol: "RTSP",
    username: "admin",
    password: "Dahua@456",
    isActive: true,
    assignedAt: new Date().toISOString(),
    deactivatedAt: null,
    notes: "Exit door",
    changedBy: "admin",
    changeReason: "Initial setup",
    cctvId: "c8",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
};

export const CCTV_LIST: CCTVItem[] = [
    { id: "c1", label: "CCTV-01", location: "Pintu Masuk Utama", status: "ONLINE",  resolution: "4K",    brand: "Hikvision", fps: 30, activeIpCctv: IP_CCTV_DATA.c1 },
    { id: "c2", label: "CCTV-02", location: "Lobby",              status: "ONLINE",  resolution: "1080p", brand: "Dahua",     fps: 25, activeIpCctv: IP_CCTV_DATA.c2 },
    { id: "c3", label: "CCTV-03", location: "Kasir 1",            status: "ONLINE",  resolution: "1080p", brand: "Axis",      fps: 25, activeIpCctv: IP_CCTV_DATA.c3 },
    { id: "c4", label: "CCTV-04", location: "Kasir 2",            status: "OFFLINE", resolution: "1080p", brand: "Hikvision", fps: 0,  activeIpCctv: IP_CCTV_DATA.c4 },
    { id: "c5", label: "CCTV-05", location: "Gudang",             status: "ONLINE",  resolution: "4K",    brand: "Dahua",     fps: 30, activeIpCctv: IP_CCTV_DATA.c5 },
    { id: "c6", label: "CCTV-06", location: "Ruang Server",       status: "MAINTENANCE", resolution: "1080p", brand: "Axis", fps: 0, activeIpCctv: IP_CCTV_DATA.c6 },
    { id: "c7", label: "CCTV-07", location: "Area Parkir",        status: "ONLINE",  resolution: "1080p", brand: "Hikvision", fps: 25, activeIpCctv: IP_CCTV_DATA.c7 },
    { id: "c8", label: "CCTV-08", location: "Pintu Keluar",       status: "ONLINE",  resolution: "4K",    brand: "Dahua",     fps: 30, activeIpCctv: IP_CCTV_DATA.c8 },
];
  